---
title: "lab 7 - HW 8"
author: "Nahomi Farington"
date: "2024-04-04"
output: html_document
---
```{r}
load("C:/Users/Owner/Desktop/Psychology/R-work/Household_Pulse_data_ph4c2.RData")
```


```{r}
summary(Household_Pulse_data)
```

```{r}
require(plyr)
require(dplyr)
require(tidyverse)
require(ggplot2)
require(stargazer)

```

```{r}
select1 <- (Household_Pulse_data$MHLTH_NEED != "NA")
d_kids <- subset(Household_Pulse_data,select1)

```

```{r}
d_kids$MentHealthKids <- as.numeric(
 (d_kids$MHLTH_NEED == "all children need mental health treatment") |
 (d_kids$MHLTH_NEED == "some but not all children") )

```

```{r}
ddply(d_kids,.(GENID_DESCRIBE), summarize, avg = mean(MentHealthKids))

```

```{r}
ols_out1 <- lm(MentHealthKids ~ -1 + GENID_DESCRIBE, data = d_kids)
stargazer(ols_out1, type = "text")

```

```{r}
ols_out1a <- lm(MentHealthKids ~ GENID_DESCRIBE, data = d_kids)
stargazer(ols_out1a, type = "text")
```

```{r}
p_avg_byrace <- ggplot(d_kids, aes(x = GENID_DESCRIBE, fill = MHLTH_NEED))
p_avg_byrace + geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "mako", begin = 0.3, end = 0.85) 

```

```{r}
ols_out2 <- lm(MentHealthKids ~ GENID_DESCRIBE + SOCIAL1, data = d_kids)
stargazer(ols_out2, type = "text")

```

```{r}
ols_out2a <- lm(MentHealthKids ~ GENID_DESCRIBE*SOCIAL1, data = d_kids)
stargazer(ols_out2a, type = "text")

```

```{r}
anova(ols_out2,ols_out2a)

```

```{r}
p_avg_byrace <- ggplot(d_kids, aes(x = GENID_DESCRIBE, fill = MHLTH_NEED))
p_avg_byrace + geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "mako", begin = 0.3, end = 0.85) +
 facet_grid(~SOCIAL1)
```

```{r}
ols_out3 <- lm(MentHealthKids ~ SOCIAL1*RRACE*EEDUC*MS + GENID_DESCRIBE, data = d_kids)
stargazer(ols_out3, type = "text")

```

```{r}
ols_out3a <- lm(MentHealthKids ~ REGION*TENURE*RRACE + MS + GENID_DESCRIBE, data = d_kids)

```

```{r}
anova(ols_out2a,ols_out3a)
```

```{r}
ols_out4 <- lm(MentHealthKids ~ REGION*RRACE*EEDUC + MS + GENID_DESCRIBE +
 REGION + ANXIOUS + WORRY + INTEREST +
 SOCIAL1 + SOCIAL2 +
 SUPPORT1 + SUPPORT2 + SUPPORT3 + SUPPORT4 + SUPPORT1EXP, data = d_kids)
stargazer(ols_out3a,ols_out4, type = "text")

```

```{r}
logit_out1 <- glm(MentHealthKids ~ REGION*RRACE*EEDUC + MS + GENID_DESCRIBE +
 REGION + ANXIOUS + WORRY + INTEREST +
 SOCIAL1 + SOCIAL2 +
 SUPPORT1 + SUPPORT2 + SUPPORT3 + SUPPORT4 + SUPPORT1EXP, data = d_kids,
 family = binomial)
stargazer(ols_out4,logit_out1, type = "text")

```

```{r}
pred_vals <- predict(logit_out1, d_kids, type = "response")
pred_model_logit1 <- (pred_vals > 0.18)
table(pred = pred_model_logit1, true = d_kids$MentHealthKids)

```

